# Generated by Django 5.1.6 on 2025-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0002_alter_aula_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotehora',
            name='horas_contratadas',
            field=models.FloatField(),
        ),
    ]
