# Generated by Django 5.1.6 on 2025-05-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0003_alter_pacotehora_horas_contratadas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('aluno', 'professor', 'data_inicio', 'hora_inicio', 'hora_fim')},
        ),
    ]
