# Generated by Django 5.1.6 on 2025-05-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0004_alter_aula_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotehora',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_hora_individuais', to='uniescolar.aluno'),
        ),
    ]
